hanoi: a1-5.cpp
	# write the command for compiling a1-5.cpp to a1-5.out
	
median: a1-4.cpp
	# this the default target to compile the C++ program, which would be executed if you just run `make` without any arguments

# this compiles the 'a0.cpp' file into an executable named 'test0.out' using g++

default: a1-4.cpp
	g++ -Wall a1-4.cpp -o a1-4.out 

# this runs the executable 'test0.out' generated by the default target above
# on Windows, use 'test0.out' instead of './test0.out'

run: a1-4.out 
	a1-4.out 

# this will delete all files with a `.out` extension in the current directory
# on Windows, use `del` instead of `rm`

 
clean:
	del *.out 
